version: '3'
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  frontend:
    command: tail -f /dev/null
    image: botium/botium-speech-frontend:${TAG}
    restart: always
    environment:
      BOTIUM_API_TOKENS:
      BOTIUM_SPEECH_PROVIDER_TTS: marytts
      BOTIUM_SPEECH_PROVIDER_STT: kaldi
      BOTIUM_SPEECH_GOOGLE_CLIENT_EMAIL:
      BOTIUM_SPEECH_GOOGLE_PRIVATE_KEY:
    volumes:
      - "./frontend/resources:/app/resources"
  watcher:
    image: botium/botium-speech-watcher:${TAG}
    restart: always
    volumes:
      - "./watcher:/app/watch"
      - "./logs/watcher:/app/logs"
  stt-en:
    image: botium/botium-speech-kaldi-en:${TAG}
    restart: always
    volumes:
      - "./logs/stt-en:/opt/logs"
  stt-de:
    image: botium/botium-speech-kaldi-de:${TAG}
    restart: always
    volumes:
      - "./logs/stt-de:/opt/logs"
  tts:
    image: botium/botium-speech-marytts:${TAG}
    restart: always
  dictate:
    image: botium/botium-speech-dictate:${TAG}
    restart: always
